Repository cert-manager/helm-tool, pull requests merged in 2024-01, with the labels that each got.

#5 Parse provided property paths
  parser/document.go
  parser/path.go
  parser/path_test.go
  render/markdown-table
Labels: dco-signoff: yes, size/L, lgtm, approved

#6 Generate JSON schema based on values.yaml
  go.mod
  go.sum
  heuristics/sniffer.go
  main.go
  parser/document.go
  parser/path.go
  parser/path_test.go
  schema/render.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#7 Add linter
  go.mod
  go.sum
  linter/diff.go
  linter/diff_test.go
  linter/linter.go
  linter/parsetemplates/funcs_serdes/funcs_serdes.go
  linter/parsetemplates/templates.go
  linter/parsetemplates/templates_test.go
  linter/parsetemplates/util.go
  main.go
  parser/document.go
  paths/path.go
  paths/path_test.go
  schema/render.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#8 Add copyright, add makefile unit-test & make 'make verify' work
  .gitignore
  heuristics/newlines.go
  heuristics/newlines_test.go
  heuristics/sniffer.go
  heuristics/sniffer_test.go
  klone.yaml
  linter/diff.go
  linter/diff_test.go
  linter/linter.go
  linter/parsetemplates/funcs_serdes/funcs_serdes.go
  linter/parsetemplates/templates.go
  linter/parsetemplates/templates_test.go
  linter/parsetemplates/util.go
  main.go
  make/02_mod.mk
  make/_shared/generate-verify/01_mod.mk
  make/_shared/generate-verify/02_mod.mk
  make/_shared/generate-verify/util/verify.sh
  make/_shared/help/help.sh
  make/_shared/oci-image/01_mod.mk
  make/_shared/tools/00_mod.mk
  make/test-unit.mk
  parser/comment.go
  parser/document.go
  parser/tags.go
  paths/path.go
  paths/path_test.go
  render/render.go
  schema/render.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#15 Fix owners file
  OWNERS
Labels: dco-signoff: yes, size/S, lgtm, approved

#16 Upgrade repository-base module
  .github/workflows/make-self-upgrade.yaml
  Makefile
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#20 BUGFIX: WithProperty and WithIndex alter sibling paths
  paths/path.go
  paths/path_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#21 Update markdown template to work with artifacthub
  examples/cert-manager/README.md
  main.go
  render/markdown-plain
  render/render.go
Labels: size/XXL, dco-signoff: yes, lgtm, approved
